import { CodeHighlight } from '@mantine/code-highlight';
import { Code } from '@mantine/core';
import { PRODUCT_NAME } from '~/app/config';
import { InternalLink } from '~/components/InternalLink';
import { PageTitle } from '~/components/PageTitle';
import { Txt } from '~/components/Txt';
import { loadCode } from '~/lib/code';
import { getRouteMetadata } from '~/lib/utils';
import { Example } from './Example';

const PATH = '/examples/basic-usage';

export const metadata = getRouteMetadata(PATH);

export default async function BasicUsageExamplePage() {
  const code = (await loadCode('app/examples/basic-usage/Example.tsx')) as string;
  return (
    <>
      <PageTitle of={PATH} />
      <Txt>
        In its most basic usage scenario, the <Code>showContextMenu</Code> function only requires you to provide an
        array of objects describing the menu items.
        <br />
        Each object in the array must have two properties: a unique <Code>key</Code> and an <Code>onClick</Code>{' '}
        handler.
        <br />
        For each item, a title will be automatically generated by “humanizing” the <Code>key</Code> value.
        <br />
        The <Code>onClick</Code> handler will be called when the user clicks on the corresponding menu item.
      </Txt>
      <CodeHighlight code={code} />
      <Txt>Right-click on the image to trigger the context menu:</Txt>
      <Example />
      <Txt>
        However, <InternalLink to="/examples/basic-configuration">there’s more</InternalLink> you can do with{' '}
        {PRODUCT_NAME}.
        <br />
        Head over to the next example to discover other features.
      </Txt>
    </>
  );
}
